### ISSUE TITLE
Errors when opening "MainForm"

### ISSUE THREAD

**Issue by develop987** [karenpayneoregon/WindowsFormsMasterDetailWithSqlServer#1]
**Error1:**
_The type "datagridviewcalendarlibrary.calendarcolumn" could not be found._
_Check that there is a link to the assembly containing this type._ 
_If this type is part of a project under development, make sure that the project has been successfully compiled using parameters
for your current platform or for any processor.__

**Error2:**
_The 'Order Date Column' variable is either not declared, or it has not been assigned a value._

**Descriprion**
I have completed:
  - I downloaded the project github.com;
  - I have opened a project;
  - I want to open 'MainForm.cs' in the constructor;
  - result: I get an error.

**USE**
Visual Studio - 2019 Community

**Error description in more detail**
The type "datagridviewcalendarlibrary.calendarcolumn" could not be found. Check that there is a link to the assembly containing this type. If this type is part of a project under development, make sure that the project has been successfully compiled using parameters for your current platform or for any processor.     
 
Instances of error (2)
1. Stack contents and line number are not available for this error.   
2. Stack contents and line number are not available for this error.  
Show information about this error   
The help section related to this error could not be found. Check the list of Windows Forms Development Time errors   
  
Messages about this error in the forum  
 
Search for messages about this error in the MSDN forums
   The 'orderdatecolumn' variable is either not declared, or it has not been assigned a value.     Go to the code  
 
Error instances (1)

1. WindowsApplication_cs MainForm.Designer.cs Row:367, column:1 Show the call stack  
 
in System.ComponentModel.Design.Serialization.CodeDomSerializerBase.Error(idesignerserializationmanager manager, String exceptionText, String helpLink)
in System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeExpression(idesignerserializationmanager manager, String name, CodeExpression expression)
in System.ComponentModel.Design.Serialization.CodeDomSerializerBase.DeserializeExpression(IDesignerSerializationManager manager, String name, CodeExpression expression)  

Show information about this error  
 
MSDN Help   

 
Messages about this error in the forum  
 
Search for messages about this error in the MSDN forums

**Picture*
![02 12 2021_14-13-36](https://user-images.githubusercontent.com/90496895/144411774-f3e6df43-e0de-4c6c-8e63-dec0813de018.png)
*

**Comment by karenpayneoregon** [comment]
I wrote this in `Visual Studio 2017` so I just downloaded the solution as this was coded on another machine.

1. Performed a rebuild on the solution in `Visual Studio 2019`
2. Double clicked on each form, all opened with no problem
3. Ran both the `VB` and `C#` examples, both worked.

With that said, if you did not perform a rebuild on the solution this would cause the errors you have encountered with error 1 and error 2.

So please perform in your case a solution `clean` then `rebuild` followed by opening each form.

**Comment by develop987** [comment]
@karenpayneoregon  
Works. 
Thanks.
